# Project Euler #2 Solution
"""
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, 
the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
"""
def fib(n):
    if n == 0 or n == 1:
        return 1
    else:
        return fib(n-1) + fib(n-2)
y = []
for i in range(35):
    y.append(fib(i))
f = []
for i in y:
    if (i%2 == 0) and (i<6000000):
        f.append(i)

print(sum(f))

